---
# This playbook deploys the whole application stack in this site.

- name: Create ssh enable docker with volume 
  hosts: test_lab
  remote_user: root

  roles:
    - lvm
    - docker_install_7
    - docker_image
    - docker_run